import { StyleSheet } from "react-native";
import { Colors } from "../../../../../constants/Colors";

const styles = StyleSheet.create({
  container: {
    backgroundColor: Colors.background,
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 30,
    fontWeight: "bold",
    color: Colors.primary,
  },
  dividerContainer: {
    width: "80%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  textDivider: { textAlignVertical: "center", color: "grey" },
  divider: {
    marginVertical: 20,
    width: "40%",
    borderBottomColor: Colors.secondary,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  input: {
    width: "80%",
    padding: 10,
    margin: 15,
    backgroundColor: "white",
    borderColor: Colors.secondary,
    borderWidth: 1,
    borderRadius: 10,
  },
  disabled: {},
  button: {
    width: "80%",
    content: "fill",
    display: "flex",
    justifyContent: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
    margin: 10,
    padding: 8,
    // backgroundColor: Colors.primary,
    borderRadius: 10,
  },
  textButton: {
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
  },
  socialButton: {
    width: "80%",
    content: "fill",
    display: "flex",
    justifyContent: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
    marginVertical: 10,
    padding: 10,
    paddingLeft: 20,
    backgroundColor: "white",
    borderColor: Colors.secondary,
    borderWidth: 1,
    borderRadius: 10,

    image: {
      width: 30,
      height: 30,
    },
  },
  text: {
    fontSize: 16,
    color: Colors.text,
  },
  flexRow: {
    width: "80%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
  },
  textPrimary: {
    fontSize: 16,
    color: "orange",
    marginVertical: 10,
  },
  loginPrimary: {
    marginLeft: 10,
    fontWeight: "bold",
  },
  inputContainer: {
    width: "80%",
    height: 50,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
    marginTop: 15,
    marginBottom: 5,
    borderColor: Colors.secondary,
    borderWidth: 1,
    borderRadius: 10,
  },
  inputIcon: {
    fontWeight: "200",
    color: Colors.secondary,
    fontSize: 20,
  },
  error: {
    width: "80%",
    color: Colors.error,
    textAlign: "left",
  },
  modal: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    height: "30%",
    backgroundColor: "white",
    borderRadius: 10,
    borderWidth: 1,
    marginVertical: 150,
  },
  buttonModal: {
    height: 30,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  textButtonModal: { color: Colors.text, fontSize: 16, fontWeight: "bold" },
});

export default styles;
